# Generated by Django 3.2.8 on 2021-11-14 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_weight',
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='exercise_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ExerciseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.exercisegroup'),
        ),
    ]
