# Generated by Django 3.2.8 on 2021-11-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_group_name_exercisegroup_exercise_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisegroup',
            old_name='user',
            new_name='username',
        ),
    ]
