# Generated by Django 3.2.8 on 2021-11-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_user_exercisegroup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisegroup',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
