# Generated by Django 3.2.8 on 2021-11-14 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_exercisegroup_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisegroup',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
