# Generated by Django 3.2.8 on 2021-11-14 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_exercisegroup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisegroup',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='exercisegroup',
            name='username',
        ),
        migrations.AddField(
            model_name='exercise',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='user.exercisegroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercisegroup',
            name='exercise_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
