# Generated by Django 3.2.8 on 2021-11-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20211114_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_group',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
