# Generated by Django 3.2.8 on 2021-11-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20211114_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisegroup',
            name='exercise_group',
            field=models.CharField(default='exercise_group', max_length=50),
        ),
    ]
