# Generated by Django 3.2.8 on 2021-11-14 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_exercise_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='user.exercisegroup'),
        ),
    ]
