# Generated by Django 3.2.8 on 2021-11-15 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_exercise_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisegroup',
            old_name='exercise_group',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='exercisegroup',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
