# Generated by Django 3.2.9 on 2021-11-16 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_rename_username_exercisegroup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_weight', models.IntegerField(default=0)),
                ('date_completed', models.DateTimeField(auto_now=True)),
                ('sets', models.IntegerField(default=0)),
                ('reps_per_set', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_group',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_weight',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExerciseGroup',
        ),
        migrations.AddField(
            model_name='userexerciselog',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlog', to='user.exercise'),
        ),
        migrations.AddField(
            model_name='userexerciselog',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='user.programme'),
        ),
    ]
