# Generated by Django 3.2.8 on 2021-11-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20211115_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='date_completed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
